spring:
  application:
    name: provider
dubbo:
  scan:
    base-packages: com.sou7h.springbootdubbo.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://127.0.0.1:2181